version: "3"

services:

  selenium-hub:
    image: selenium/hub:3.141.59-dubnium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:3.141.59-dubnium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"

  firefox:
    image: selenium/node-firefox-debug:3.141.59-dubnium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  e2e-tests:
    build: "."
    image: e2e-tests:latest
    working_dir: /code
    command: "npm run test -- --hostname selenium-hub"
    depends_on:
      - selenium-hub
      - chrome
      - firefox
