version: "3"

services:

  selenium-hub:
    image: selenium/hub:${TAG}
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "sh", "./opt/bin/check-grid.sh"]
      interval: 3s
      timeout: 20s
      retries: 5
    logging:
      driver: none

  chrome:
    image: selenium/node-chrome-debug:${TAG}
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"
    logging:
      driver: none

  firefox:
    image: selenium/node-firefox-debug:${TAG}
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    logging:
      driver: none

  e2e-tests:
    build: "."
    image: e2e-tests:latest
    working_dir: /code
    env_file: .env
    command: ["sh", "./wait-for-grid.sh", "selenium-hub", "--", "npm test", "--", "--hostname selenium-hub"]
    depends_on:
      - selenium-hub
      - chrome
      - firefox
